# everything below was generated by clap_complete
# this is missing stack/service completions, feel free to open a PR

# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_blent_global_optspecs
	string join \n app-path= v/verbose q/quiet help version
end

function __fish_blent_needs_command
	# Figure out if the current invocation already has a command.
	set -l cmd (commandline -opc)
	set -e cmd[1]
	argparse -s (__fish_blent_global_optspecs) -- $cmd 2>/dev/null
	or return
	if set -q argv[1]
		# Also print the command, so this can be used to figure out what it is.
		echo $argv[1]
		return 1
	end
	return 0
end

function __fish_blent_using_subcommand
	set -l cmd (__fish_blent_needs_command)
	test -z "$cmd"
	and return 1
	contains -- $cmd[1] $argv
end

complete -c blent -n "__fish_blent_needs_command" -l app-path -d 'Directory in which to look for stacks [default: ~/app]' -r -F
complete -c blent -n "__fish_blent_needs_command" -s v -l verbose -d 'Increase logging verbosity'
complete -c blent -n "__fish_blent_needs_command" -s q -l quiet -d 'Decrease logging verbosity'
complete -c blent -n "__fish_blent_needs_command" -l help -d 'Print help'
complete -c blent -n "__fish_blent_needs_command" -l version -d 'Print version'
complete -c blent -n "__fish_blent_needs_command" -f -a "status" -d 'Print a summary of stacks'
complete -c blent -n "__fish_blent_needs_command" -f -a "up" -d 'Create and start stacks'
complete -c blent -n "__fish_blent_needs_command" -f -a "down" -d 'Stop and remove stacks'
complete -c blent -n "__fish_blent_needs_command" -f -a "logs" -d 'View output from services'
complete -c blent -n "__fish_blent_needs_command" -f -a "update" -d 'Update stack images'
complete -c blent -n "__fish_blent_using_subcommand status" -l app-path -d 'Directory in which to look for stacks [default: ~/app]' -r -F
complete -c blent -n "__fish_blent_using_subcommand status" -s d -l detailed -d 'Show details about services'
complete -c blent -n "__fish_blent_using_subcommand status" -s v -l verbose -d 'Increase logging verbosity'
complete -c blent -n "__fish_blent_using_subcommand status" -s q -l quiet -d 'Decrease logging verbosity'
complete -c blent -n "__fish_blent_using_subcommand status" -l help -d 'Print help'
complete -c blent -n "__fish_blent_using_subcommand up" -l app-path -d 'Directory in which to look for stacks [default: ~/app]' -r -F
complete -c blent -n "__fish_blent_using_subcommand up" -s a -l all -d 'Operate on all known services'
complete -c blent -n "__fish_blent_using_subcommand up" -s f -l force-recreate -d 'Recreate services even if they are up to date'
complete -c blent -n "__fish_blent_using_subcommand up" -s v -l verbose -d 'Increase logging verbosity'
complete -c blent -n "__fish_blent_using_subcommand up" -s q -l quiet -d 'Decrease logging verbosity'
complete -c blent -n "__fish_blent_using_subcommand up" -l help -d 'Print help'
complete -c blent -n "__fish_blent_using_subcommand down" -l app-path -d 'Directory in which to look for stacks [default: ~/app]' -r -F
complete -c blent -n "__fish_blent_using_subcommand down" -s a -l all -d 'Operate on all known services'
complete -c blent -n "__fish_blent_using_subcommand down" -s r -l remove-orphans -d 'Remove undefined services'
complete -c blent -n "__fish_blent_using_subcommand down" -s v -l verbose -d 'Increase logging verbosity'
complete -c blent -n "__fish_blent_using_subcommand down" -s q -l quiet -d 'Decrease logging verbosity'
complete -c blent -n "__fish_blent_using_subcommand down" -l help -d 'Print help'
complete -c blent -n "__fish_blent_using_subcommand logs" -l app-path -d 'Directory in which to look for stacks [default: ~/app]' -r -F
complete -c blent -n "__fish_blent_using_subcommand logs" -s f -l follow -d 'Follow log output'
complete -c blent -n "__fish_blent_using_subcommand logs" -s v -l verbose -d 'Increase logging verbosity'
complete -c blent -n "__fish_blent_using_subcommand logs" -s q -l quiet -d 'Decrease logging verbosity'
complete -c blent -n "__fish_blent_using_subcommand logs" -l help -d 'Print help'
complete -c blent -n "__fish_blent_using_subcommand update" -l app-path -d 'Directory in which to look for stacks [default: ~/app]' -r -F
complete -c blent -n "__fish_blent_using_subcommand update" -s a -l all -d 'Operate on all known services'
complete -c blent -n "__fish_blent_using_subcommand update" -s p -l prune-dangling -d 'Prune dangling images after updating'
complete -c blent -n "__fish_blent_using_subcommand update" -s v -l verbose -d 'Increase logging verbosity'
complete -c blent -n "__fish_blent_using_subcommand update" -s q -l quiet -d 'Decrease logging verbosity'
complete -c blent -n "__fish_blent_using_subcommand update" -l help -d 'Print help'
